// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8xz5G7OEmJec_ZN54etAgAJHkj8Uub-4',
    appId: '1:596387925054:web:d06d402676c55a9ba5956f',
    messagingSenderId: '596387925054',
    projectId: 'arithmania2024',
    authDomain: 'arithmania2024.firebaseapp.com',
    storageBucket: 'arithmania2024.appspot.com',
    measurementId: 'G-2E4DTKGCRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP3WLpxxaOMWv9HWqqatPheoQA_rZ1KuI',
    appId: '1:596387925054:android:199e2a5bf9ce29c4a5956f',
    messagingSenderId: '596387925054',
    projectId: 'arithmania2024',
    storageBucket: 'arithmania2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIS-rDTHmQLVS2peqfl-nu4VsvjuISpmI',
    appId: '1:596387925054:ios:8cac76f6374d03b9a5956f',
    messagingSenderId: '596387925054',
    projectId: 'arithmania2024',
    storageBucket: 'arithmania2024.appspot.com',
    iosBundleId: 'com.example.arithmaniaFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIS-rDTHmQLVS2peqfl-nu4VsvjuISpmI',
    appId: '1:596387925054:ios:44a99afc841314d1a5956f',
    messagingSenderId: '596387925054',
    projectId: 'arithmania2024',
    storageBucket: 'arithmania2024.appspot.com',
    iosBundleId: 'com.example.arithmaniaFrontend.RunnerTests',
  );
}
